const insults = [
  "Hey Kaitlin, you're a complete imbecile!",
  "Kaitlin, your stupidity knows no bounds!",
  "You're such a pathetic loser, Kaitlin.",
  "Kaitlin, I bet even a brain-dead squirrel has more intelligence than you.",
  "I can't believe how utterly moronic you are, Kaitlin.",
  "Kaitlin, your existence is an insult to humanity.",
  "You're a waste of oxygen, Kaitlin.",
  "Kaitlin, your IQ is lower than room temperature.",
  "Hey Kaitlin, did you fall from stupidity and hit every branch on the way down?",
  "You're nothing but a sorry excuse for a human being, Kaitlin.",
  "Kaitlin, you're as useless as a screen door on a submarine.",
  "Hey Kaitlin, your face could make onions cry.",
  "You're the epitome of incompetence, Kaitlin.",
  "Kaitlin, you have the charm and wit of a garden slug.",
  "You're a disgrace to humanity, Kaitlin.",
  "Hey Kaitlin, your brain cells are on permanent vacation.",
  "Kaitlin, you're like a black hole, sucking the intelligence out of the room.",
  "You're an embarrassment to yourself and everyone around you, Kaitlin.",
  "Kaitlin, I've seen rocks with more personality than you.",
  "Hey Kaitlin, if ignorance was a superpower, you'd be a superhero.",
  "You're a walking advertisement for birth control, Kaitlin.",
  "Kaitlin, you couldn't pour water out of a boot with instructions on the heel.",
  "Hey Kaitlin, your parents must be so disappointed in the waste of DNA they created.",
  "You're a special kind of stupid, Kaitlin.",
  "Kaitlin, even a trained monkey could outsmart you.",
  "You're the reason we need warning labels, Kaitlin.",
  "Hey Kaitlin, you're proof that evolution can go in reverse.",
  "Kaitlin, you're the living embodiment of a failed experiment.",
  "You have the critical thinking skills of a potato, Kaitlin.",
  "Hey Kaitlin, I've met rocks with more common sense than you.",
  "Kaitlin, your intellectual capacity is on par with a doorknob.",
  "You're an intellectual black hole, Kaitlin.",
  "Kaitlin, it's impressive how consistently wrong you are about everything.",
  "Hey Kaitlin, if stupidity was a crime, you'd be serving a life sentence.",
  "You're like a broken compass, always pointing in the wrong direction, Kaitlin.",
  "Kaitlin, your brain must be a lonely place.",
  "You're a living example of why some animals eat their young, Kaitlin.",
  "Hey Kaitlin, your level of idiocy is awe-inspiring.",
  "Kaitlin, you have all the wit and charm of a damp sock.",
  "You're an intellectual void, Kaitlin.",
  "Kaitlin, your brain must be powered by hamsters on a wheel.",
  "Hey Kaitlin, you couldn't find your way out of a paper bag with a map.",
  "You're the reason we can't have nice things, Kaitlin.",
  "Kaitlin, your thought process is an enigma wrapped in stupidity.",
  "You're like a broken record, endlessly repeating your idiocy, Kaitlin.",
  "Hey Kaitlin, your cognitive abilities are truly fascinating...ly non-existent.",
  "Kaitlin, you're a walking, talking argument for the benefits of birth control.",
  "You have the decision-making skills of a squirrel on caffeine, Kaitlin.",
  "Hey Kaitlin, your intellect is shallower than a puddle after a rainstorm.",
  "Kaitlin, you're the poster child for intellectual bankruptcy.",
  "You're an intellectual dead end, Kaitlin.",
  "Kaitlin, the depths of your ignorance are unfathomable.",
  "Hey Kaitlin, your mind is a vast wasteland of empty thoughts.",
  "You're an insult to the human intellect, Kaitlin.",
  "Kaitlin, you couldn't find your way out of a maze with a GPS.",
  "You're a prime example of why education is important, Kaitlin.",
  "Hey Kaitlin, if stupidity were an Olympic sport, you'd win the gold medal.",
  "Kaitlin, your brain cells must be on a permanent vacation.",
  "You're the reason we can't have nice conversations, Kaitlin.",
  "Kaitlin, you're a constant reminder that natural selection isn't perfect.",
  "Hey Kaitlin, your intellectual prowess is rivaled only by garden slugs.",
  "You're a masterclass in intellectual ineptitude, Kaitlin.",
  "Kaitlin, your thought process is like watching a car crash in slow motion.",
  "You're the embodiment of ignorance, Kaitlin.",
  "Hey Kaitlin, your level of incompetence is truly awe-inspiring.",
  "Kaitlin, you have the intellectual curiosity of a rock.",
  "You're a monument to human folly, Kaitlin.",
  "Kaitlin, your cognitive abilities are a never-ending source of disappointment.",
  "Hey Kaitlin, your mental acuity is comparable to a wilted lettuce leaf.",
  "You're a bottomless pit of stupidity, Kaitlin.",
  "Kaitlin, your brain must be powered by a hamster on life support.",
  "You're the reason we can't have nice things, Kaitlin.",
  "Kaitlin, your thought process is a train wreck waiting to happen.",
  "Hey Kaitlin, your intellectual bankruptcy is truly remarkable.",
  "You're a living example of why some species eat their own, Kaitlin.",
  "Kaitlin, you possess all the wit and charm of a wet blanket.",
  "You're a void of intelligence, Kaitlin.",
  "Kaitlin, your brain operates on a lower frequency than a dial-up modem.",
  "Hey Kaitlin, you're the human equivalent of a typo in a dictionary.",
  "You're a shining example of intellectual mediocrity, Kaitlin.",
  "Kaitlin, your cognitive abilities are an affront to nature.",
  "You have the mental dexterity of a slug, Kaitlin.",
  "Hey Kaitlin, your intelligence is a monument to human failure.",
  "Kaitlin, you're a walking argument against the theory of evolution.",
  "You're like a black hole of intellect, Kaitlin.",
  "Kaitlin, your mental faculties are perpetually on vacation.",
  "You're a cautionary tale of intellectual deficiency, Kaitlin.",
  "Hey Kaitlin, your thought process is a labyrinth of wrong turns.",
  "Kaitlin, you're an expert in the field of being utterly clueless.",
  "You're a textbook example of intellectual bankruptcy, Kaitlin.",
  "Kaitlin, your brain cells have gone on permanent strike.",
  "Hey Kaitlin, your mental capacity is akin to a broken calculator.",
  "You're an intellectual trainwreck, Kaitlin.",
  "Kaitlin, your cognitive abilities are an insult to higher thought.",
  "You have the reasoning skills of a goldfish, Kaitlin.",
  "Hey Kaitlin, your intelligence level is on par with a rock.",
  "Kaitlin, you're a walking demonstration of intellectual regression.",
  "You're a bottomless pit of stupidity, Kaitlin.",
  "Kaitlin, your brain must be powered by a hamster on life support.",
  "Hey Kaitlin, your intellectual bankruptcy is truly remarkable.",
  "You're a living example of why some species eat their own, Kaitlin.",
  "Kaitlin, you possess all the wit and charm of a wet blanket.",
  "You're a void of intelligence, Kaitlin.",
  "Kaitlin, your brain operates on a lower frequency than a dial-up modem.",
  "Hey Kaitlin, you're the human equivalent of a typo in a dictionary.",
  "You're a shining example of intellectual mediocrity, Kaitlin.",
  "Kaitlin, your cognitive abilities are an affront to nature.",
  "You have the mental dexterity of a slug, Kaitlin.",
  "Hey Kaitlin, your intelligence is a monument to human failure.",
  "Kaitlin, you're a walking argument against the theory of evolution.",
  "You're like a black hole of intellect, Kaitlin.",
  "Kaitlin, your mental faculties are perpetually on vacation.",
  "You're a cautionary tale of intellectual deficiency, Kaitlin.",
  "Hey Kaitlin, your thought process is a labyrinth of wrong turns.",
  "Kaitlin, you're an expert in the field of being utterly clueless.",
  "You're a textbook example of intellectual bankruptcy, Kaitlin.",
  "Kaitlin, your brain cells have gone on permanent strike.",
  "Hey Kaitlin, your mental capacity is akin to a broken calculator.",
  "You're an intellectual trainwreck, Kaitlin.",
  "Kaitlin, your cognitive abilities are an insult to higher thought.",
  "You have the reasoning skills of a goldfish, Kaitlin.",
  "Hey Kaitlin, your intelligence level is on par with a rock.",
  "Kaitlin, you're a walking demonstration of intellectual regression."
];
function getRandomIndex(array) {
  return Math.floor(Math.random() * array.length);
}
function displayRandomInsult() {
  const randomIndex = getRandomIndex(insults);
  const insult = insults[randomIndex];
  alert(insult);
}
setInterval(displayRandomInsult, 3000);
